import React from 'react';
import {Link} from 'react-router-dom';

class Sidebar extends React.Component {
	constructor(props) {
		super(props);

		this.state = {
			colors: {
				html: [
					{hex: '#657383', name: 'Slate Gray'},
					{hex: '#616D7E', name: 'Jet Gray'},
					{hex: '#646D7E', name: 'Mist Blue'},
					{hex: '#566D7E', name: 'Marble Blue'},
					{hex: '#737CA1', name: 'Slate Blue'},
					{hex: '#4863A0', name: 'Steel Blue'},
					{hex: '#2B547E', name: 'Blue Jay'},
					{hex: '#2B3856', name: 'Dark Slate Blue'},
					{hex: '#151B54', name: 'Midnight Blue'},
					{hex: '#000080', name: 'Navy Blue'},
					{hex: '#342D7E', name: 'Blue Whale'},
					{hex: '#15317E', name: 'Lapis Blue'},
					{hex: '#151B8D', name: 'Denim Dark Blue'},
					{hex: '#0000A0', name: 'Earth Blue'},
					{hex: '#0020C2', name: 'Cobalt Blue'},
					{hex: '#0041C2', name: 'Blueberry Blue'},
					{hex: '#2554C7', name: 'Sapphire Blue'},
					{hex: '#1569C7', name: 'Blue Eyes'},
					{hex: '#2B60DE', name: 'Royal Blue'},
					{hex: '#1F45FC', name: 'Blue Orchid'},
					{hex: '#6960EC', name: 'Blue Lotus'},
					{hex: '#736AFF', name: 'Light Slate Blue'},
					{hex: '#357EC7', name: 'Windows Blue'},
					{hex: '#368BC1', name: 'Glacial Blue Ice'},
					{hex: '#488AC7', name: 'Silk Blue'},
					{hex: '#3090C7', name: 'Blue Ivy'},
					{hex: '#659EC7', name: 'Blue Koi'},
					{hex: '#87AFC7', name: 'Columbia Blue'},
					{hex: '#95B9C7', name: 'Baby Blue'},
					{hex: '#728FCE', name: 'Light Steel Blue'},
					{hex: '#2B65EC', name: 'Ocean Blue'},
					{hex: '#306EFF', name: 'Blue Ribbon'},
					{hex: '#157DEC', name: 'Blue Dress'},
					{hex: '#1589FF', name: 'Dodger Blue'},
					{hex: '#6495ED', name: 'Cornflower Blue'},
					{hex: '#6698FF', name: 'Sky Blue'},
					{hex: '#38ACEC', name: 'Butterfly Blue'},
					{hex: '#56A5EC', name: 'Iceberg'},
					{hex: '#5CB3FF', name: 'Crystal Blue'},
					{hex: '#3BB9FF', name: 'Deep Sky Blue'},
					{hex: '#79BAEC', name: 'Denim Blue'},
					{hex: '#82CAFA', name: 'Light Sky Blue'},
					{hex: '#82CAFF', name: 'Day Sky Blue'},
					{hex: '#A0CFEC', name: 'Jeans Blue'},
					{hex: '#B7CEEC', name: 'Blue Angel'},
					{hex: '#B4CFEC', name: 'Pastel Blue'},
					{hex: '#C2DFFF', name: 'Sea Blue'},
					{hex: '#C6DEFF', name: 'Powder Blue'},
					{hex: '#AFDCEC', name: 'Coral Blue'},
					{hex: '#ADDFFF', name: 'Light Blue'},
					{hex: '#BDEDFF', name: 'Robin Egg Blue'},
					{hex: '#CFECEC', name: 'Pale Blue Lily'},
					{hex: '#E0FFFF', name: 'Light Cyan'},
					{hex: '#EBF4FA', name: 'Water'},
					{hex: '#F0F8FF', name: 'AliceBlue'},
					{hex: '#F0FFFF', name: 'Azure'},
					{hex: '#CCFFFF', name: 'Light Slate'},
					{hex: '#93FFE8', name: 'Light Aquamarine'},
					{hex: '#9AFEFF', name: 'Electric Blue'},
					{hex: '#7FFFD4', name: 'Aquamarine'},
					{hex: '#00FFFF', name: 'Cyan or Aqua'},
					{hex: '#7DFDFE', name: 'Tron Blue'},
					{hex: '#57FEFF', name: 'Blue Zircon'},
					{hex: '#8EEBEC', name: 'Blue Lagoon'},
					{hex: '#50EBEC', name: 'Celeste'},
					{hex: '#4EE2EC', name: 'Blue Diamond'},
					{hex: '#81D8D0', name: 'Tiffany Blue'},
					{hex: '#92C7C7', name: 'Cyan Opaque'},
					{hex: '#77BFC7', name: 'Blue Hosta'},
					{hex: '#78C7C7', name: 'Northern Lights Blue'},
					{hex: '#48CCCD', name: 'Medium Turquoise'},
					{hex: '#43C6DB', name: 'Turquoise'},
					{hex: '#46C7C7', name: 'Jellyfish'},
					{hex: '#7BCCB5', name: 'Blue green'},
					{hex: '#43BFC7', name: 'Macaw Blue Green'},
					{hex: '#3EA99F', name: 'Light Sea Green'},
					{hex: '#3B9C9C', name: 'Dark Turquoise'},
					{hex: '#438D80', name: 'Sea Turtle Green'},
					{hex: '#348781', name: 'Medium Aquamarine'},
					{hex: '#307D7E', name: 'Greenish Blue'},
					{hex: '#5E7D7E', name: 'Grayish Turquoise'},
					{hex: '#4C787E', name: 'Beetle Green'},
					{hex: '#008080', name: 'Teal'},
					{hex: '#4E8975', name: 'Sea Green'},
					{hex: '#78866B', name: 'Camouflage Green'},
					{hex: '#848b79', name: 'Sage Green'},
					{hex: '#617C58', name: 'Hazel Green'},
					{hex: '#728C00', name: 'Venom Green'},
					{hex: '#667C26', name: 'Fern Green'},
					{hex: '#254117', name: 'Dark Forest Green'},
					{hex: '#306754', name: 'Medium Sea Green'},
					{hex: '#347235', name: 'Medium Forest Green'},
					{hex: '#437C17', name: 'Seaweed Green'},
					{hex: '#387C44', name: 'Pine Green'},
					{hex: '#347C2C', name: 'Jungle Green'},
					{hex: '#347C17', name: 'Shamrock Green'},
					{hex: '#348017', name: 'Medium Spring Green'},
					{hex: '#4E9258', name: 'Forest Green'},
					{hex: '#6AA121', name: 'Green Onion'},
					{hex: '#4AA02C', name: 'Spring Green'},
					{hex: '#41A317', name: 'Lime Green'},
					{hex: '#3EA055', name: 'Clover Green'},
					{hex: '#6CBB3C', name: 'Green Snake'},
					{hex: '#6CC417', name: 'Alien Green'},
					{hex: '#4CC417', name: 'Green Apple'},
					{hex: '#52D017', name: 'Yellow Green'},
					{hex: '#4CC552', name: 'Kelly Green'},
					{hex: '#54C571', name: 'Zombie Green'},
					{hex: '#99C68E', name: 'Frog Green'},
					{hex: '#89C35C', name: 'Green Peas'},
					{hex: '#85BB65', name: 'Dollar Bill Green'},
					{hex: '#8BB381', name: 'Dark Sea Green'},
					{hex: '#9CB071', name: 'Iguana Green'},
					{hex: '#B2C248', name: 'Avocado Green'},
					{hex: '#9DC209', name: 'Pistachio Green'},
					{hex: '#A1C935', name: 'Salad Green'},
					{hex: '#7FE817', name: 'Hummingbird Green'},
					{hex: '#59E817', name: 'Nebula Green'},
					{hex: '#57E964', name: 'Stoplight Go Green'},
					{hex: '#64E986', name: 'Algae Green'},
					{hex: '#5EFB6E', name: 'Jade Green'},
					{hex: '#00FF00', name: 'Green'},
					{hex: '#5FFB17', name: 'Emerald Green'},
					{hex: '#87F717', name: 'Lawn Green'},
					{hex: '#8AFB17', name: 'Chartreuse'},
					{hex: '#6AFB92', name: 'Dragon Green'},
					{hex: '#98FF98', name: 'Mint green'},
					{hex: '#B5EAAA', name: 'Green Thumb'},
					{hex: '#C3FDB8', name: 'Light Jade'},
					{hex: '#CCFB5D', name: 'Tea Green'},
					{hex: '#B1FB17', name: 'Green Yellow'},
					{hex: '#BCE954', name: 'Slime Green'},
					{hex: '#EDDA74', name: 'Goldenrod'},
					{hex: '#EDE275', name: 'Harvest Gold'},
					{hex: '#FFE87C', name: 'Sun Yellow'},
					{hex: '#FFFF00', name: 'Yellow'},
					{hex: '#FFF380', name: 'Corn Yellow'},
					{hex: '#FFFFC2', name: 'Parchment'},
					{hex: '#FFFFCC', name: 'Cream'},
					{hex: '#FFF8C6', name: 'Lemon Chiffon'},
					{hex: '#FFF8DC', name: 'Cornsilk'},
					{hex: '#F5F5DC', name: 'Beige'},
					{hex: '#FBF6D9', name: 'Blonde'},
					{hex: '#FAEBD7', name: 'AntiqueWhite'},
					{hex: '#F7E7CE', name: 'Champagne'},
					{hex: '#FFEBCD', name: 'BlanchedAlmond'},
					{hex: '#F3E5AB', name: 'Vanilla'},
					{hex: '#ECE5B6', name: 'Tan Brown'},
					{hex: '#FFE5B4', name: 'Peach'},
					{hex: '#FFDB58', name: 'Mustard'},
					{hex: '#FFD801', name: 'Rubber Ducky Yellow'},
					{hex: '#FDD017', name: 'Bright Gold'},
					{hex: '#EAC117', name: 'Golden brown'},
					{hex: '#F2BB66', name: 'Macaroni and Cheese'},
					{hex: '#FBB917', name: 'Saffron'},
					{hex: '#FBB117', name: 'Beer'},
					{hex: '#FFA62F', name: 'Cantaloupe'},
					{hex: '#E9AB17', name: 'Bee Yellow'},
					{hex: '#E2A76F', name: 'Brown Sugar'},
					{hex: '#DEB887', name: 'BurlyWood'},
					{hex: '#FFCBA4', name: 'Deep Peach'},
					{hex: '#C9BE62', name: 'Ginger Brown'},
					{hex: '#E8A317', name: 'School Bus Yellow'},
					{hex: '#EE9A4D', name: 'Sandy Brown'},
					{hex: '#C8B560', name: 'Fall Leaf Brown'},
					{hex: '#D4A017', name: 'Orange Gold'},
					{hex: '#C2B280', name: 'Sand'},
					{hex: '#C7A317', name: 'Cookie Brown'},
					{hex: '#C68E17', name: 'Caramel'},
					{hex: '#B5A642', name: 'Brass'},
					{hex: '#ADA96E', name: 'Khaki'},
					{hex: '#C19A6B', name: 'Camel brown'},
					{hex: '#CD7F32', name: 'Bronze'},
					{hex: '#C88141', name: 'Tiger Orange'},
					{hex: '#C58917', name: 'Cinnamon'},
					{hex: '#AF9B60', name: 'Bullet Shell'},
					{hex: '#AF7817', name: 'Dark Goldenrod'},
					{hex: '#B87333', name: 'Copper'},
					{hex: '#966F33', name: 'Wood'},
					{hex: '#806517', name: 'Oak Brown'},
					{hex: '#827839', name: 'Moccasin'},
					{hex: '#827B60', name: 'Army Brown'},
					{hex: '#786D5F', name: 'Sandstone'},
					{hex: '#493D26', name: 'Mocha'},
					{hex: '#483C32', name: 'Taupe'},
					{hex: '#6F4E37', name: 'Coffee'},
					{hex: '#835C3B', name: 'Brown Bear'},
					{hex: '#7F5217', name: 'Red Dirt'},
					{hex: '#7F462C', name: 'Sepia'},
					{hex: '#C47451', name: 'Orange Salmon'},
					{hex: '#C36241', name: 'Rust'},
					{hex: '#C35817', name: 'Red Fox'},
					{hex: '#C85A17', name: 'Chocolate'},
					{hex: '#CC6600', name: 'Sedona'},
					{hex: '#E56717', name: 'Papaya Orange'},
					{hex: '#E66C2C', name: 'Halloween Orange'},
					{hex: '#F87217', name: 'Pumpkin Orange'},
					{hex: '#F87431', name: 'Construction Cone Orange'},
					{hex: '#E67451', name: 'Sunrise Orange'},
					{hex: '#FF8040', name: 'Mango Orange'},
					{hex: '#F88017', name: 'Dark Orange'},
					{hex: '#FF7F50', name: 'Coral'},
					{hex: '#F88158', name: 'Basket Ball Orange'},
					{hex: '#F9966B', name: 'Light Salmon'},
					{hex: '#E78A61', name: 'Tangerine'},
					{hex: '#E18B6B', name: 'Dark Salmon'},
					{hex: '#E77471', name: 'Light Coral'},
					{hex: '#F75D59', name: 'Bean Red'},
					{hex: '#E55451', name: 'Valentine Red'},
					{hex: '#E55B3C', name: 'Shocking Orange'},
					{hex: '#FF0000', name: 'Red'},
					{hex: '#FF2400', name: 'Scarlet'},
					{hex: '#F62217', name: 'Ruby Red'},
					{hex: '#F70D1A', name: 'Ferrari Red'},
					{hex: '#F62817', name: 'Fire Engine Red'},
					{hex: '#E42217', name: 'Lava Red'},
					{hex: '#E41B17', name: 'Love Red'},
					{hex: '#DC381F', name: 'Grapefruit'},
					{hex: '#C34A2C', name: 'Chestnut Red'},
					{hex: '#C24641', name: 'Cherry Red'},
					{hex: '#C04000', name: 'Mahogany'},
					{hex: '#C11B17', name: 'Chilli Pepper'},
					{hex: '#9F000F', name: 'Cranberry'},
					{hex: '#990012', name: 'Red Wine'},
					{hex: '#8C001A', name: 'Burgundy'},
					{hex: '#954535', name: 'Chestnut'},
					{hex: '#7E3517', name: 'Blood Red'},
					{hex: '#8A4117', name: 'Sienna'},
					{hex: '#7E3817', name: 'Sangria'},
					{hex: '#800517', name: 'Firebrick'},
					{hex: '#810541', name: 'Maroon'},
					{hex: '#7D0541', name: 'Plum Pie'},
					{hex: '#7E354D', name: 'Velvet Maroon'},
					{hex: '#7D0552', name: 'Plum Velvet'},
					{hex: '#7F4E52', name: 'Rosy Finch'},
					{hex: '#7F5A58', name: 'Puce'},
					{hex: '#7F525D', name: 'Dull Purple'},
					{hex: '#B38481', name: 'Rosy Brown'},
					{hex: '#C5908E', name: 'Khaki Rose'},
					{hex: '#C48189', name: 'Pink Bow'},
					{hex: '#C48793', name: 'Lipstick Pink'},
					{hex: '#E8ADAA', name: 'Rose'},
					{hex: '#ECC5C0', name: 'Rose Gold'},
					{hex: '#EDC9AF', name: 'Desert Sand'},
					{hex: '#FDD7E4', name: 'Pig Pink'},
					{hex: '#FCDFFF', name: 'Cotton Candy'},
					{hex: '#FFDFDD', name: 'Pink Bubble Gum'},
					{hex: '#FBBBB9', name: 'Misty Rose'},
					{hex: '#FAAFBE', name: 'Pink'},
					{hex: '#FAAFBA', name: 'Light Pink'},
					{hex: '#F9A7B0', name: 'Flamingo Pink'},
					{hex: '#E7A1B0', name: 'Pink Rose'},
					{hex: '#E799A3', name: 'Pink Daisy'},
					{hex: '#E38AAE', name: 'Cadillac Pink'},
					{hex: '#F778A1', name: 'Carnation Pink'},
					{hex: '#E56E94', name: 'Blush Red'},
					{hex: '#F660AB', name: 'Hot Pink'},
					{hex: '#FC6C85', name: 'Watermelon Pink'},
					{hex: '#F6358A', name: 'Violet Red'},
					{hex: '#F52887', name: 'Deep Pink'},
					{hex: '#E45E9D', name: 'Pink Cupcake'},
					{hex: '#E4287C', name: 'Pink Lemonade'},
					{hex: '#F535AA', name: 'Neon Pink'},
					{hex: '#FF00FF', name: 'Magenta'},
					{hex: '#E3319D', name: 'Dimorphotheca Magenta'},
					{hex: '#F433FF', name: 'Bright Neon Pink'},
					{hex: '#D16587', name: 'Pale Violet Red'},
					{hex: '#C25A7C', name: 'Tulip Pink'},
					{hex: '#CA226B', name: 'Medium Violet Red'},
					{hex: '#C12869', name: 'Rogue Pink'},
					{hex: '#C12267', name: 'Burnt Pink'},
					{hex: '#C25283', name: 'Bashful Pink'},
					{hex: '#C12283', name: 'Dark Carnation Pink'},
					{hex: '#B93B8F', name: 'Plum'},
					{hex: '#7E587E', name: 'Viola Purple'},
					{hex: '#571B7E', name: 'Purple Iris'},
					{hex: '#583759', name: 'Plum Purple'},
					{hex: '#4B0082', name: 'Indigo'},
					{hex: '#461B7E', name: 'Purple Monster'},
					{hex: '#4E387E', name: 'Purple Haze'},
					{hex: '#614051', name: 'Eggplant'},
					{hex: '#5E5A80', name: 'Grape'},
					{hex: '#6A287E', name: 'Purple Jam'},
					{hex: '#7D1B7E', name: 'Dark Orchid'},
					{hex: '#A74AC7', name: 'Purple Flower'},
					{hex: '#B048B5', name: 'Medium Orchid'},
					{hex: '#6C2DC7', name: 'Purple Amethyst'},
					{hex: '#842DCE', name: 'Dark Violet'},
					{hex: '#8D38C9', name: 'Violet'},
					{hex: '#7A5DC7', name: 'Purple Sage Bush'},
					{hex: '#7F38EC', name: 'Lovely Purple'},
					{hex: '#8E35EF', name: 'Purple'},
					{hex: '#893BFF', name: 'Aztech Purple'},
					{hex: '#8467D7', name: 'Medium Purple'},
					{hex: '#A23BEC', name: 'Jasmine Purple'},
					{hex: '#B041FF', name: 'Purple Daffodil'},
					{hex: '#C45AEC', name: 'Tyrian Purple'},
					{hex: '#9172EC', name: 'Crocus Purple'},
					{hex: '#9E7BFF', name: 'Purple Mimosa'},
					{hex: '#D462FF', name: 'Heliotrope Purple'},
					{hex: '#E238EC', name: 'Crimson'},
					{hex: '#C38EC7', name: 'Purple Dragon'},
					{hex: '#C8A2C8', name: 'Lilac'},
					{hex: '#E6A9EC', name: 'Blush Pink'},
					{hex: '#E0B0FF', name: 'Mauve'},
					{hex: '#C6AEC7', name: 'Wisteria Purple'},
					{hex: '#F9B7FF', name: 'Blossom Pink'},
					{hex: '#D2B9D3', name: 'Thistle'},
					{hex: '#E9CFEC', name: 'Periwinkle'},
					{hex: '#EBDDE2', name: 'Lavender Pinocchio'},
					{hex: '#E3E4FA', name: 'Lavender blue'},
					{hex: '#FDEEF4', name: 'Pearl'},
					{hex: '#FFF5EE', name: 'SeaShell'},
					{hex: '#FEFCFF', name: 'Milk White'},
					{hex: '#FFFFFF', name: 'White'},
				]
			}
		}
	}

	render() { 
		const {colors} = this.state;
		
		return (
			<div className="Sidebar">
				{colors.html.map((value, index) => {
					const {hex} = value;

					return (
						<Link to={`/${hex.substr(1)}`} key={index} className="Sidebar__coloritem" style={{backgroundColor:`${hex}`, color: `${hex}`}}>
							<span className="Sidebar__colorname"><small>#</small>{hex.substr(1)}</span>
						</Link>
					)
				})}
			</div>
		);
	}
}

export default Sidebar;